### ISSUE TITLE
Logo Proposal for Synesthesia

### ISSUE THREAD

**Issue by area55git** [ismay/synesthesia#37]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Would you like me to design a logo for your project?

**Comment by ismay** [comment]
Hi! Yeah that would be cool. Might be nice to have a logo in the readme 😊

**Comment by area55git** [comment]
Perfect, in the course of the day I send it.
Do you have any suggestions or favorite colors for your logo?

**Comment by ismay** [comment]
Cool! No suggestions or ideas really, I’ll leave that to you 👍

**Comment by area55git** [comment]
I can not see the video.

**Comment by ismay** [comment]
You mean that the image doesn’t change? It’s supposed to be like that. The image is what I converted to the sound with this library

**Comment by area55git** [comment]
I had the audio off. :)

**Comment by ismay** [comment]
Ah ok, yeah then it isn’t that exciting 😋

**Comment by area55git** [comment]
Hi, what do you think about this proposal?

[![LOGO_PROPOSAL_FOR_SINESTHESIA.jpg](https://s9.postimg.cc/ef7h3pdn3/LOGO_PROPOSAL_FOR_SINESTHESIA.jpg)](https://postimg.cc/image/69pf5jpe3/)

**Comment by area55git** [comment]
I already corrected the spelling error, do you like this design?

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_SINESTHESIA_2.jpg](https://s9.postimg.cc/nfgo1f9cf/LOGO_PROPOSAL_FOR_SINESTHESIA_2.jpg)](https://postimg.cc/image/md6hivqiz/)

**Comment by area55git** [comment]
I applied your suggestions and it was great .. !!

[![LOGO_PROPOSAL_FOR_SINESTHESIA_2.jpg](https://s9.postimg.cc/e2ywzn8cf/LOGO_PROPOSAL_FOR_SINESTHESIA_2.jpg)](https://postimg.cc/image/45nw6l0qj/)

I love the result!

[![LOGO_PROPOSAL_FOR_SINESTHESIA_3.jpg](https://s9.postimg.cc/gx22d7ku7/LOGO_PROPOSAL_FOR_SINESTHESIA_3.jpg)](https://postimg.cc/image/yaccs2g57/)

If you like I send you the link of the files and I make a PR

**Comment by ismay** [comment]
Ha yeah that’s great! Awesome 👏👏🎉 And so quick. Yeah if you’d like to send me a pr that would be perfect 😊👌

**Comment by area55git** [comment]
Finished, enjoy it!

# [FILE DOWNLOAD](https://drive.google.com/open?id=10IoAqyYKtUq7I_vYWk-sO5WSgNSnzZMp)

[![MONTAJE_PROPUESTA_OPENMF_9.jpg](https://s14.postimg.cc/62h9w6iq9/MONTAJE_PROPUESTA_OPENMF_9.jpg)](https://postimg.cc/image/99btft365/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
PR #44
